name: Build and Trigger Readthedocs

on:
  push:
    paths:
      - 'docs/**'           # Trigger for changes in the docs directory
      - '**/*.rst'          # Trigger for any RST files
      - '**/*.man'          # Trigger for any man page files
  pull_request:
    paths:
      - 'docs/**'           # Same triggers for pull requests
      - '**/*.rst'
      - '**/*.man'

jobs:
  build-docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build Documentation Locally
        run: |
          sphinx-build -b html docs/ docs/_build

  trigger-rtd:
    needs: build-docs  # Ensures this job runs after the build-docs job
    runs-on: ubuntu-22.04

    steps:
      - name: Generate Webhook Signature
        id: generate-signature
        run: |
          # Define the webhook secret
          SECRET="${{ secrets.RTD_WEBHOOK_SECRET }}"

          # Create a minimal JSON payload with "ref" set to the branch name
          PAYLOAD=$(jq -n --arg ref "${{ github.ref_name }}" '{ref: $ref}')

          # Generate HMAC SHA256 signature for the payload
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')

          # Save the signature and payload as environment variables
          echo "SIGNATURE=$SIGNATURE" >> $GITHUB_ENV
          echo "PAYLOAD=$PAYLOAD" >> $GITHUB_ENV

      - name: Trigger Read the Docs Build
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -H "X-Hub-Signature-256: sha256=${{ env.SIGNATURE }}" \
               -d "${{ env.PAYLOAD }}" \
               https://readthedocs.org/api/v2/webhook/ovis-rtd/273836/
