name: Build and Trigger Readthedocs

on:
  push:
    paths:
      - 'docs/**'           # Trigger for changes in the docs directory
      - '**/*.rst'          # Trigger for any RST files
      - '**/*.man'          # Trigger for any man page files
  pull_request:
    paths:
      - 'docs/**'           # Same triggers for pull requests
      - '**/*.rst'
      - '**/*.man'

jobs:
  build-docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build Documentation Locally
        run: |
          sphinx-build -b html docs/ docs/_build

  trigger-rtd:
    needs: build-docs  # Ensures this job runs after the build-docs job
    runs-on: ubuntu-22.04

    steps:
      - name: Generate Webhook Signature
        id: generate-signature
        run: |
          # Define the webhook secret
          SECRET="${{ secrets.RTD_WEBHOOK_SECRET }}"

          # Payload to be sent to Read the Docs (can be any relevant data)
          PAYLOAD="{}"  # The payload to sign, you can adjust this based on what Read the Docs expects

          # Generate HMAC SHA256 signature using OpenSSL
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')

          # Save the signature as an environment variable for the next step
          echo "SIGNATURE=$SIGNATURE" >> $GITHUB_ENV

      - name: Trigger Read the Docs Build
        run: |
          curl -X POST \
               -H "Authorization: Token ${{ secrets.RTD_WEBHOOK_TOKEN }}" \
               -H "X-Hub-Signature: sha256=$SIGNATURE" \
               https://readthedocs.org/api/v2/webhook/ovis-rtd/273836/
