name: Build and Trigger Readthedocs

on:
  push:
    paths:
      - 'docs/**'           # Trigger for changes in the docs directory
      - '**/*.rst'          # Trigger for any RST files
      - '**/*.man'          # Trigger for any man page files
  pull_request:
    paths:
      - 'docs/**'           # Same triggers for pull requests
      - '**/*.rst'
      - '**/*.man'

jobs:
  generate-rst:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      
      - name: Check if docs/man is empty
        id: check_docs_man
        run: |
          # Check if docs/man directory is empty
          if [ -z "$(ls -A docs/man)" ]; then
            echo "docs/man is empty. Converting all .man files."
            echo "docs_man=true" >> $GITHUB_ENV
          else
            echo "docs/man is not empty. Checking for modified .man files."
            echo "docs_man=false" >> $GITHUB_ENV
          fi

      - name: Convert .man files to .rst if needed
        if: env.docs_man == 'true' || github.event.head_commit.modified || github.event.head_commit.added
        run: |
          # Convert all .man files to .rst if docs/man is empty or specific .man files were modified
          find ldms/src ldms/man -name "*.man" -print0 | while IFS= read -r -d '' man_file; do
              target_dir="docs/man/$(echo "$man_file" | sed -e 's|^ldms/src/||' -e 's|^ldms/man/||' -e 's/\.man$/.rst/')"
              
              # Ensure the target directory exists
              mkdir -p "$(dirname "$target_dir")"

              # Convert the .man file to .rst using pandoc
              pandoc -f man "$man_file" -s -o "$target_dir"
              echo "Converted $man_file to $target_dir"
          done

      - name: Generate or Update index.rst files
        run: |
          # Update index.rst in each directory to include newly converted .rst files
          find docs/man -type d | while IFS= read -r dir; do
              # List all .rst files in the current directory (excluding index.rst)
              rst_files=$(find "$dir" -maxdepth 1 -name "*.rst" ! -name "index.rst" | sort)

              # If there are .rst files in this directory, create or update index.rst file
              if [ ! -z "$rst_files" ]; then
                  # Create or update the index.rst file
                  echo "Generating/updating index.rst in $dir"

                  # Start the index file with a title
                  echo "Index of $dir" > "$dir/index.rst"
                  echo "===================" >> "$dir/index.rst"
                  echo "" >> "$dir/index.rst"

                  # Add links to all .rst files in the directory
                  for rst_file in $rst_files; do
                      base_name=$(basename "$rst_file")
                      echo "* :doc:`$base_name`" >> "$dir/index.rst"
                  done
              fi
          done

      - name: Commit and Push Generated RST and index.rst Files
        if: steps.check_docs_man.outputs.docs_man == 'true' || github.event.head_commit.modified || github.event.head_commit.added
        run: |
          # Commit and push the changes if any .rst or index.rst files were generated or modified
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/man/*.rst docs/man/*/index.rst
          
          # Check if there are any files to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generated .rst files from .man pages and updated index.rst files"
            git push origin HEAD
      
  build-docs:
    needs: generate-rst
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build Documentation Locally
        run: |
          sphinx-build -b html docs/ docs/_build

  trigger-rtd:
    needs: build-docs  # Ensures this job runs after the build-docs job
    runs-on: ubuntu-22.04

    steps:
      - name: Generate Webhook Signature and Trigger RTD
        run: |
          # Define the webhook secret
          SECRET="${{ secrets.RTD_WEBHOOK_SECRET }}"

          # Create a JSON payload with "ref" set to the branch name
          PAYLOAD="{\"ref\": \"${GITHUB_REF_NAME}\"}"

          # Generate HMAC SHA256 signature for the payload
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')

          # Trigger the Read the Docs webhook
          curl -X POST \
               -H "Content-Type: application/json" \
               -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
               -d "$PAYLOAD" \
               https://readthedocs.org/api/v2/webhook/ovis-rtd/273836/
